# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

# Enabled
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes

# Disabled
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
COMBO_ENABLE = no
RING_BUFFERED_6KRO_REPORT_ENABLE = no
AUDIO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LEADER_ENABLE = no
MIDI_ENABLE = no
UNICODE_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = no

# Not supported
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
BLUETOOTH_ENABLE = no
SPLIT_KEYBOARD = no

